### ISSUE TITLE
Add link to RSS

### ISSUE THREAD

**Issue by IRus** [madhead/madhead.github.io#18]
Sample: 
```
<link rel="alternate" type="application/atom+xml" title="Madhead Blog" href="/index.xml"/>
```

**Comment by madhead** [comment]
I guess this theme ([BluestNight](https://themes.gohugo.io/bluestnight/)) already provides it at the upper right part of the page:

![image](https://user-images.githubusercontent.com/577360/33292773-72ff9870-d3db-11e7-9635-181e212d55e3.png)

**Comment by IRus** [comment]
Lol, doesn't mention this at all.

Firefox has built-in button to indicate that page has feeds. Home page actually have this link, but post page - no:

![image](https://user-images.githubusercontent.com/493656/33293093-41fb5bd0-d3d4-11e7-9b53-94919a5310f7.png)

**Comment by IRus** [comment]
Example of page with feed link tag:

![image](https://user-images.githubusercontent.com/493656/33293135-65ccd37c-d3d4-11e7-846a-71366f12262d.png)

**Comment by madhead** [comment]
Got you. Not sure how this works, but there is a link in HTML markup as well:

    <link rel="alternate" type="application/rss+xml" title="madhead Feed" href="https://madhead.me/index.xml">

It's not `atom`, but `rss`, but I don't think it should be critical?

**Comment by madhead** [comment]
Crap. No got you. Need to read carefully.

**Comment by IRus** [comment]
`rss` looks right for `https://github.com/madhead/BluestNight/blob/3392c5f3bf9cfbc8e59c503f1868fa2518b673ea/layouts/rss.xml`

found source https://github.com/madhead/BluestNight/blob/3392c5f3bf9cfbc8e59c503f1868fa2518b673ea/layouts/_default/baseof.html#L37

not sure why it not used on post page

**Comment by IRus** [comment]
Yep, works!
